function [BW,maskedImage] = segmentImage(RGB)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(RGB) segments image RGB using
%  auto-generated code from the imageSegmenter app. The final segmentation
%  is returned in BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 27-Aug-2020
%----------------------------------------------------


% Adjust data to span data range.
RGB = imadjust(RGB);

% Convert RGB image into L*a*b* color space.
X = rgb2lab(RGB);

% Auto clustering
s = rng;
rng('default');
L = imsegkmeans(single(X),2,'NumAttempts',2);
rng(s);
BW = L == 2;

% Invert mask
BW = imcomplement(BW);

% Active contour
iterations = 30;
BW = activecontour(X, BW, iterations, 'Chan-Vese');

% Fill holes
BW = imfill(BW, 'holes');

% Dilate mask with line
length = 3.000000;
angle = 0.000000;
se = strel('line', length, angle);
BW = imdilate(BW, se);

% Erode mask with disk
radius = 32;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imerode(BW, se);

% Clear borders
BW = imclearborder(BW);

% Erode mask with disk
radius = 32;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imerode(BW, se);

% Erode mask with disk
radius = 20;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imerode(BW, se);

% Create masked image.
maskedImage = RGB;
maskedImage(repmat(~BW,[1 1 3])) = 0;
end

